### ISSUE TITLE
Error: ‘url-retrieve’ backend does not support FILES

### ISSUE THREAD

**Issue by ghost** [tomjakubowski/sprunge.el#3]
When I invoke sprunge-buffer or sprunge-region, I get this error:

```
request--url-retrieve-preprocess-settings: ‘url-retrieve’ backend does not support FILES.
```

What does this mean? Is it possible I'm missing a dependency?

Emacs version: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, X toolkit, Xaw scroll bars) of 2017-01-17.

**Comment by ghost** [comment]
I don't know why. The error is gone.

**Comment by tomjakubowski** [comment]
I think you might get this error if the `url-retrieve` backend is selected. Maybe curl wasn't installed until now?

**Comment by ghost** [comment]
Ah, right! `curl` wasn't installed, yes!

**Comment by tomjakubowski** [comment]
It's good to know that curl is a requirement. I'll add it to the README when I get a chance. Thanks :-)
